[package]
name = "vision_quest"
version = "0.1.0"
authors = ["zwetsloot robert jan <zwetsloot.robert.jan@techcross.co.jp>"]

[dependencies]
serde_json = "1.0.22"
serde_derive = "1.0.69"
serde = "1.0.69"
conrod = { version = "0.60.0", features = ["glium", "winit"] }
conrod_derive = "0.1"
